### PR TITLE
Fix number parser

### PR DESCRIPTION
**Pull request by bencochran**
The number parsing was having trouble with greedy matching (int matched before decimals, decimals before decimals with exponents, and “e” before “e+”). This fixes all that and adds a slew of tests.

### CODE REVIEW

**Comment by robrix** [comment]
Whoa, thank you so much!

@joshvera: would you mind taking a quick glance at this?

**Comment by joshvera** [comment]
Looks good. Thanks @bencochran!

**Comment by robrix** [comment]
@joshvera: Thanks :blush:

@bencochran: I’ve added you as a collaborator. PRs are still preferred for non-trivial changes, but it should be a little more convenient now :blush:

Thanks again!

**Comment by bencochran** [comment]
@joshvera Thanks for the merge!

@robrix Thanks for adding me :bow:

**Pull request merged**
