### PR TITLE
Swift 1.2

### PR DESCRIPTION
**Pull request by amackworth**
Updated Either and made the requisite changes. :grin:

### CODE REVIEW

**Comment by robrix** [comment]
Wow, thank you! I wasn’t likely to get around to this until Friday otherwise.

With Either and the others, I was thinking I wouldn’t merge until Swift 1.2 is out of beta, but I might instead tag them now and then merge to `master`. What do you think?

**Comment by amackworth** [comment]
Sounds good to me! Personally, the master branch of a repo should always represent the latest (non-broken) build, not necessarily the stable build. After all, that's why we have tags!

Also, I opened this for use in TesseractCore, and merging all of the changes to `master` will make life easier over there.

:pray:

**Comment by robrix** [comment]
Works for me. I’ll do `Either` first.

**Comment by robrix** [comment]
@amackworth Merged `Either` and `Prelude`’s `swift-1.2` branches in. Could you please bump the submodule ref to `master`?

**Comment by amackworth** [comment]
There ya go!

**Comment by robrix** [comment]
Danke!

**Comment by robrix** [comment]
Tagged Madness. Now let’s :shipit:!

**Pull request merged**
